### ISSUE TITLE
Breaking changes in avrdude

### ISSUE THREAD

**Issue by pfeyffer** [vonnieda/AVRFuses#13]
AVRDude Version 7.0 removed the command line option "-s" for safemode prompting. An error message about the invalid parameter is given.
AVRFuses breaks when calling AVRDude with the -s parameter while trying to read the fuses.
I suggest to drop the -s parameter from the AVRDude call since it has become obsolete.

**Comment by gpb01** [comment]
Yes, please, I think you have just to comment out line 487 of AVRFusesController.m

Thanks in advance.

**Comment by kr15uk** [comment]
Any update on this?! Thanks
