### ISSUE TITLE
version 1.6.1 not delivered by outupdate, not mentioned on the homepage

### ISSUE THREAD

**Issue by core-code** [vonnieda/AVRFuses#16]
http://www.vonnieda.org/AVRFuses/appcast.xml => still points to 1.5.2

is this on purpose?

**Comment by vonnieda** [comment]
It's on purpose. I removed the auto-update function in the latest version because it is hard to maintain and out of date. Releases are now maintained here: https://github.com/vonnieda/AVRFuses/releases

I'll get the webpage updated to point to it.
