### ISSUE TITLE
Can't run with AVRDude 8.0

### ISSUE THREAD

**Issue by dimitar-a-dimitrov** [vonnieda/AVRFuses#17]
I noticed that there is something wrong when using AVRDude 8.0. The app issues FAILURE in the log form. I debugged it and figure out that there is a case sensitive search for the string Version. However on AVRDude 8.0 it prints version - all lower case. So the fix should be in AVRFuseController.m, at line 427, as follows:

range = [line rangeOfString: @"version" options:NSCaseInsensitiveSearch];

I tried to create PR but there was a drama with my credentials.

Best regards

**Comment by jon-daemon** [comment]
I also have avrdude 8 installed and I cannot use it with a usbasp clone I tried.

**Comment by dimitar-a-dimitrov** [comment]
> I also have avrdude 8 installed and I cannot use it with a usbasp clone I tried.

Can you try to debug in Xcode to see what is failing, @jon-daemon ?

**Comment by jon-daemon** [comment]
I don't have it installed currently. I grabbed a previous avrdude version from Arduino app and it's working with that.

**Comment by vonnieda** [comment]
Thanks @dimitar-a-dimitrov - new release at https://github.com/vonnieda/AVRFuses/releases/tag/v1.6.2
