### ISSUE TITLE
Problem with MainMenu.nib

### ISSUE THREAD

**Issue by bigjohnson** [vonnieda/AVRFuses#2]
I try recompile the app, but Xcode say that MainMenu.nib is not in a correct format.
If I substitute the file getting it from the compiled version the program is compiled without problems.
Please could you check the gitub file?
Thanks.

Alberto

Tested with:
Osx 10.6.8
Xcode 3.2.6

**Comment by vonnieda** [comment]
You are using a very old version of Xcode. Can you upgrade?
