### ISSUE TITLE
ATtiny2313A autodetect broken

### ISSUE THREAD

**Issue by Megatokio** [vonnieda/AVRFuses#8]
AVRFuses version 1.5.0:
when used with avrdude 6.3:
autodetection of ATtiny2313A is broken.

AVRFuses does not detect an ATtiny2313A properly, probably it tries to use avrdude -p attiny2313A.
But avrdude does not know the ATtiny2313A but can use ATtiny2313 instead. Differences are minor and probably no differences for programming.

An ATtiny2313A could simply be autodetected as an ATtiny2313 instead.

autodetect results in:

SUCCESS
device not found

older versions:
printed null or crashed

**Comment by felias-fogg** [comment]
Actually, the ATtinys were not in the list. In the next release they are.

**Comment by Megatokio** [comment]
nice to hear. i still have some in my drawers. :-)

**Comment by vonnieda** [comment]
This has been released in v1.6.1.

**Comment by Megatokio** [comment]
glad to hear. i'll give it a try in my next 5V application. :-)
