### ISSUE TITLE
http://vonnieda.org/AVRFuses not available

### ISSUE THREAD

**Issue by brainstorm** [vonnieda/AVRFuses#9]
"More information available at http://vonnieda.org/AVRFuses"

leads to nginx 403 Forbidden:

<img width="1052" alt="Skärmavbild 2019-06-27 kl  13 19 30" src="https://user-images.githubusercontent.com/175587/60231904-3a501800-98de-11e9-9573-b435417e7c3a.png">

**Comment by vonnieda** [comment]
Thanks! Fixed the README. If you saw this somewhere else, please let me know where.

Thanks,
Jason
